/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'varun' at '8/9/16 9:15 PM' with Gradle 2.14.1
 *
 * @author varun, @date 8/9/16 9:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
