/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'varun' at '30/12/16 11:16 PM' with Gradle 2.14.1
 *
 * @author varun, @date 30/12/16 11:16 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
